### ISSUE TITLE
New maintainer wanted

### ISSUE THREAD

**Issue by xsuchy** [fedora-copr/flask-whooshee#64]
This project has been started by Slavek Kabrda, but he does not have time for it anymore. Copr team took this project as we use it. But this is at the bottom of our priorities. 
If you like this project and you want to maintain it, then please drop a comment here.

**Comment by frenzymadness** [comment]
I'm not personally interested in this project but can offer my help in case you need to fix something related to new Pythons etc. The question I have is whether you need to keep Python 2 support here.

**Comment by xsuchy** [comment]
Our team does not need python2 at all. And because even EPEL7 supports py3 I think we can kill py2 with a fanfare. :)

**Comment by greyli** [comment]
Hi, I would like to help to maintain this project. See more background here: https://github.com/greyli/flask-extension-status

Please grant me the repository maintenance and PyPI permission (ID: greyli). I will help to release a new version to fix the installation issue (https://github.com/fedora-copr/flask-whooshee/pull/85) in the 0.9.0 version.

**Comment by xsuchy** [comment]
I added you. Check your email for an invitation.

**Comment by praiskup** [comment]
Thank you, @greyli

**Comment by praiskup** [comment]
Sorry @greyli, I forgot ... I've added you to the PyPI project now.  Would you mind adding a git tag and finishing the 0.9.1 release?

**Comment by greyli** [comment]
> Sorry @greyli, I forgot ... I've added you to the PyPI project now. Would you mind adding a git tag and finishing the 0.9.1 release?

It's okay. Sure, I will do it!

**Comment by greyli** [comment]
0.9.1 version released:

* https://github.com/fedora-copr/flask-whooshee/releases/tag/v0.9.1
* https://pypi.org/project/flask-whooshee/
