### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by frenzymadness** [fedora-copr/flask-whooshee#66]
Hello.

I'm going to update flexmock in Fedora to its latest version which breaks builds of flask-whooshee but the compatibility is already fixed here. Could you please do a new release so I can prepare an update in Fedora?

**Comment by praiskup** [comment]
I think we can, sometime next week?

**Comment by praiskup** [comment]
5959b894202b7911c9dcaadadfcfc1953de8c37a

**Comment by praiskup** [comment]
Actually 8ab106706c2320f44f1a6ef5718ecdcb61455a04 :)
