### ISSUE TITLE
Flask whooshee fixes

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/flask-whooshee#75]
https://github.com/fedora-copr/flask-whooshee/pull/73
https://github.com/fedora-copr/flask-whooshee/pull/74

**Comment by xsuchy** [comment]
And https://src.fedoraproject.org/rpms/python-flask-whooshee/pull-requests

**Comment by praiskup** [comment]
[released](https://github.com/fedora-copr/flask-whooshee/releases/tag/v0.9.0)
